#!/bin/bash
urlencoder(){
ip=$1
echo "ip is $ip"
i=0
len=${#ip}
len=$(( len - 1 ))
echo $len
op=''
while [ $i -lt $len ]; 
do
	temp=`echo ${ip:$i:1}`
	echo $temp
	temp2=`python -c "import urllib, sys; print urllib.quote(sys.argv[1])" $temp`
	op="$op$temp2"
	
	i=$(( i + 1 ))
done 
echo $op
}

user="naireeta"
password="\$intel"

echo initial $user

echo "---------------------"
echo `echo $user | sed  's/\$/\\\$/p' | sed -n 1p`
echo "---------------------"

urlencoder `echo $user | sed  's/\$/\\\$/p' | sed -n 1p`
user=$op
echo "user is $user"
urlencoder `echo $password | sed 's/\$/\\\$/p' | sed -n 1p`
password=$op
echo "password is $password"
